/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "m3/thrift/m3_constants.h"

namespace tally { namespace m3 { namespace thrift {

const m3Constants g_m3_constants;

m3Constants::m3Constants() {
}

}}} // namespace

