/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef m3_CONSTANTS_H
#define m3_CONSTANTS_H

#include "m3/thrift/m3_types.h"

namespace tally { namespace m3 { namespace thrift {

class m3Constants {
 public:
  m3Constants();

};

extern const m3Constants g_m3_constants;

}}} // namespace

#endif
