cc_library(
    name = "tally",
    srcs = glob([
        "src/*.h",
    ]) + glob([
        "src/*.cc",
    ]),
    hdrs = glob([
        "include/tally/*.h",
    ]),
    linkstatic = 1,
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
)
